alias vim='nvim'
alias ytpl='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" "$1"'
alias zsh='nvim ~/.zshrc'
alias zz='source ~/.zshrc && echo Config reloaded'
alias a='cd && clear'
alias d='cd $(find . -type d -name ".git" -prune -o -type d -print | fzf) && clear && ls'
alias n='nvim .'
alias cc='cd ~/.config && bash ~/.config/hypr/scripts/cg-notify.sh && nvim .'
alias ch='cd ~/.config/hypr && bash ~/.config/hypr/scripts/cg-notify.sh && nvim .'
alias cs='cd ~/.config/shell && bash ~/.config/hypr/scripts/cg-notify.sh && nvim .'
alias cn='cd ~/.config/nvim && bash ~/.config/hypr/scripts/cg-notify.sh && nvim .'
alias cg='cd ~/.config/ghostty && bash ~/.config/hypr/scripts/cg-notify.sh && nvim .'
alias cw='cd ~/.config/waybar && bash ~/.config/hypr/scripts/cg-notify.sh && nvim .'
alias ls='lsd'
alias nv='nvim $(fzf -m --preview="bat --color=always {}")'
alias tt='tmux new-session -d -s dev -c ~ -n nvim ";" new-window -c ~ -n zsh ";" select-window -t nvim'
alias activate='source .venv/bin/activate --active'
alias paint='kitty icat'
alias ti='selected_dir=$(find ~ -type d 2>/dev/null | fzf --prompt="Select directory: ") && tmux new-session -s $(basename "$selected_dir") -c $selected_dir -n nvim ";" new-window -c $selected_dir -n zsh ";" select-window -t nvim'
alias ta='tmux attach -t'
